config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
	<div class="inner">
	  <p class="app-footer"><%= copyright_generator %></p>
	</div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Michael Quintero</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
	<p>
		<%= copyright_generator %>
	</p>
	<p>
	  <a href="#">Back to top</a>
	</p>
</footer>

app/views/shared/_blog_header.html.erb
<div class="blog-header">
	<div class="container">
	   <h1 class="blog-title">My Blog</h1>
	   <p class="lead blog-description">An example blog template built with bootstrap.</p>
   		<span>
	  <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
	  	</span>
	  	<span class="btn btn-secondary">
	  <%= link_to 'Topics', topics_path %>
	  	</span>
	</div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Michael Quintero", root_path, class: 'navbar-brand' %>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <%= nav_helper 'nav-link', 'li' %>  
	      <%= login_helper 'nav-link' %>  
	    </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Welcome to my personal website!  I have a variety of different hobbies.  I've recently gained a love for development which is why I decided to put this website together.  I enjoy pretty much anything outdoors and I just love life.  Click on any of the icons below to learn more about me.</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Additional References</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/Mikeq13/Mikeq13"<%= fa_icon "github" %></a></li>
      <li><a href="https://www.instagram.com/mike.quintero13/"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://www.facebook.com/michael.quintero.52"><%= fa_icon "facebook" %></a></li>
      <li><a href="https://twitter.com/Demyze_ghosTa"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://www.linkedin.com/in/michael-quintero-8a9b48110/"><%= fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
   <% if @portfolio_item.errors.any? %>
      <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label class="btn btn-primary">
        Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>
      <div class="form-group">
        <label class="btn btn-primary">
        Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows:13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2> Technologies Used: </h2>

    <div> 
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
      
      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div>
  <div><%= link_to "Home", root_path %></body></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    	<%= link_to "View All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p> 
    	<%= copyright_generator %>		
  	</p>
  </div>
</footer>

app/views/shared/_portfolio_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <ul> 
    <%= f.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <a href="#" class="btn btn-primary">Main call to action</a>
      <a href="#" class="btn btn-secondary">Secondary action</a>
    </p>
  </div>
</section>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
       <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">This is my portfolio view.  I've created a portfolio album to show you my ability to format and develop!  This has been great to do.  I'm looking forward to making this happen.  </p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %> 
            <%= portfolio_login_helper "text-white" %>
          </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-dark"> 
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Michael Quintero</a>
      <button class="navbar-toggler fa fa-bars" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  </div>
</div>